### ISSUE TITLE
Make use of solver setting from settings.yaml

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteModels.jl#24]
Use these values instead of hard-coded values.
```
initial:
    ...
    depower:   25.0        # initial depower settings    [%]
solver:
    abs_tol: 0.0006        # absolute tolerance of the DAE solver [m, m/s]
    rel_tol: 0.001         # relative tolerance of the DAE solver [-]
    max_iter:  200         # max number of iterations of the steady-state-solver
```
